---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
      app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql
    tier: mysql
  loadBalancerIP: 192.168.99.110
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  # labels so that we can bind a Service to this Pod
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_i
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql

