---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - name: wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050
  loadBalancerIP: 192.168.99.111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress_i
          imagePullPolicy: Never
          ports:
          - containerPort: 5050
            name: wordpress

